name: docs-remove-stale-reviews

on:
    schedule:
        # 42 minutes after 0:00 UTC on Sundays
        - cron: "42 0 * * 0"
    workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: write
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
    remove:
        uses: nvidia-merlin/.github/.github/workflows/docs-remove-stale-reviews-common.yaml@main
